name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
      
    # - name: Build C#
    #   run: dotnet build

    # - name: C# Tests
    #   run: dotnet test

    - name: install dependencies
      run: npm install
      working-directory: DotnetTemplate.Web

    - name: Build typescript
      run: npm run build
      working-directory: DotnetTemplate.Web

    - name: Run TS linter
      uses: icrawl/action-eslint@v1
    
    - name: typescript tests
      run: npm t
      working-directory: DotnetTemplate.Web
